name: Build and Release Product Service

on:
  push:
    branches:
      - master
    paths:
      - 'product-service/**'
  pull_request:
    branches:
      - master
    paths:
      - 'product-service/**'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Get Maven version
        id: mvnver
        run: echo "VERSION=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Clean, build and push Docker image
        run: |
          cd product-service
          ./mvnw clean package
          docker build -t pipebarreto/product-service:${{ steps.mvnver.outputs.VERSION }} -f Dockerfile .
          docker push pipebarreto/product-service:${{ steps.mvnver.outputs.VERSION }}
          cd ..

      - name: Trigger Jenkins updatemanifest job
        run: |
          curl -X POST "${{ secrets.JENKINS_URL }}/job/updatemanifest/buildWithParameters" \
            --user "${{ secrets.JENKINS_USER }}:${{ secrets.JENKINS_TOKEN }}" \
            --data-urlencode "DOCKERTAG=${{ steps.mvnver.outputs.VERSION }}" \
            --data-urlencode "NAME=product-service"