name: Java Lint (Checkstyle)

on:
  push:
    paths:
      - '**.java'
      - '**/pom.xml'
  pull_request:
    paths:
      - '**.java'
      - '**/pom.xml'
  workflow_dispatch:

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Generate Javadoc
        run: ./mvnw javadoc:javadoc

      - name: Upload Javadoc
        uses: actions/upload-artifact@v4
        with:
          name: javadoc
          path: '**/target/site/apidocs'

      - name: Run Checkstyle
        run: ./mvnw checkstyle:check -fae