name: Java Lint (Checkstyle and Javadoc)

on:
  push:
    paths:
      - '**.java'
      - '**/pom.xml'
  pull_request:
    paths:
      - '**.java'
      - '**/pom.xml'
  workflow_dispatch:

jobs:
  checkstyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Generate Javadoc
        run: ./mvnw javadoc:javadoc

      - name: Copy Javadoc to docs folder
        run: |
          rm -rf docs
          mkdir -p docs
          cp -r */target/site/apidocs/* docs/ || cp -r target/site/apidocs/* docs/ || echo "No apidocs found"

      - name: Commit and push Javadoc
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add docs
          git commit -m "docs: update Javadoc [skip ci]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Run Checkstyle
        run: ./mvnw checkstyle:check -fae