name: Scan User Service Image

on:
  push:
    paths:
      - 'user-service/**'
  pull_request:
    paths:
      - 'user-service/**'
  workflow_dispatch:

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout only user-service folder
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            user-service
          fetch-depth: 1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build Docker image
        run: |
          cd user-service
          ./mvnw clean package
          docker build -t user-service:test .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'user-service:test'
          format: table
          exit-code: 1
          ignore-unfixed: true
          vuln-type: 'library'