name: Scan API Gateway Image

on:
  push:
    paths:
      - 'api-gateway/**'
  pull_request:
    paths:
      - 'api-gateway/**'

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout only api-gateway folder
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            api-gateway
          fetch-depth: 1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Build Docker image
        run: |
          cd api-gateway
          ./mvnw clean package
          docker build -t api-gateway:test .

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'api-gateway:test'
          format: table
          exit-code: 1
          ignore-unfixed: true
          vuln-type: 'library'